name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main, develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint
